class MigrateEloToGlicko2 < ActiveRecord::Migration[7.1]
  # Temporary model definition for the old EloHistory table
  class EloHistory < ApplicationRecord
    self.table_name = :elo_histories
    belongs_to :profile
    belongs_to :leaderboard
    belongs_to :match
  end

  def up
    # Set default values for existing leaderboard ratings
    LeaderboardRating.update_all(
      rating: 1500.0,
      rating_deviation: 350.0,
      volatility: 0.06
    )

    # In a real-world scenario with a large dataset, this would be a more complex
    # data migration, likely run in batches in a background job.
    # For this project, we'll do a simple data migration.
    # We are not migrating old elo history as it is not compatible with Glicko-2.
    # New rating history will be generated by the RatingCalculationJob.
  end

  def down
    # This migration is not reversible as it involves data transformation.
    # If you need to revert, you would need to restore from a backup.
    raise ActiveRecord::IrreversibleMigration
  end
end